---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86158.
--- DateTime: 2026/9/11 16:25
---
-- 参数列表
local voucherId = ARGV[1]   -- 优惠券id（用于判断库存是否充足）
local userId = ARGV[2]  -- 用户id（用于判断用户是否下过单）
local orderId = ARGV[3]  -- 订单id（用于判断订单是否已存在）
-- 构造缓存数据key
local stockKey = 'seckill:stock:' .. voucherId -- 库存key
local orderKey = 'seckill:order:' .. voucherId -- 订单key
-- 脚本业务
-- 判断库存是否充足
if tonumber(redis.call('get', stockKey)) <= 0 then
    -- 库存不足，返回1
    return 1
end
-- 判断用户是否下过单 SISMEMBER orderKey userId，SISMEMBER：判断Set集合中是否存在某个元素，存在返回1，不存在放回0
if redis.call('sismember', orderKey, userId) == 1 then
    -- 存在，说明用户已经下单，返回2
    return 2
end
-- 缓存中预先扣减库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
-- 下单（保存用户） sadd orderKey userId
redis.call('sadd', orderKey, userId)
-- 发送消息到队列，通知订单服务下单成功
redis.call('xadd', 'stream.orders', '*','userId', userId, 'voucherId', voucherId, 'id', orderId)
-- 有下单资格，允许下单，返回0
return 0
