---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86158.
--- DateTime: 2026/9/10 22:12
---
-- 锁的key
local key = KEYS[1]
-- 当前线程标识
local threadId = ARGV[1]
-- 获取锁中的线程标识
local id = redis.call('get', key)
-- 比较当前线程标识是否和锁中的线程标识一致
if (id == threadId) then
    -- 一致，释放锁
    return redis.call('del', key)
end
-- 不一致，返回0，表示释放锁失败
return 0